version: '3.9'
services:
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=shimon
      - POSTGRES_PASSWORD=ShimonTest123!
      - POSTGRES_DB=simple_bank
      #volumes:
      #- /Users/shimonyaniv/Desktop/golang/simple_bank/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    environment:
      - DB_SOURCE=postgresql://shimon:ShimonTest123!@postgres:5432/simple_bank?sslmode=disable
    depends_on:
      - postgres
    entrypoint: ["/app/wait-for.sh", "-t5", "-q", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]